SET NAMES utf8;
--科目テーブル
DROP TABLE IF EXISTS COURSE;
CREATE TABLE IF NOT EXISTS COURSE(
    MID INTEGER NOT NULL COMMENT'専攻ID'
    ,CID INTEGER AUTO_INCREMENT COMMENT'科目ID'
    ,CNAME VARCHAR(50) NOT NULL COMMENT'科目名'
    ,CTYPE INTEGER DEFAULT 0 NOT NULL COMMENT'区分'
    ,CREDIT INTEGER DEFAULT 2 NOT NULL COMMENT'単位数'
    ,WEEKDAY INTEGER  COMMENT'曜日'
    ,CTIME INTEGER  COMMENT'時限'
    ,Teacher VARCHAR(45) NOT NULL DEFAULT '未定' COMMENT'授業先生'
    ,STD_STATE INTEGER DEFAULT 0 NOT NULL COMMENT'選択人数'
    ,STD_MAX INTEGER DEFAULT 0 NOT NULL COMMENT'上限'
    ,STD INTEGER DEFAULT 0 NOT NULL COMMENT'現在人数'
    ,CPREID INTEGER DEFAULT 0 NOT NULL COMMENT'先修ID'
    ,CMODE INTEGER DEFAULT 0 NOT NULL COMMENT'授業形態'
    ,PRIMARY KEY(CID)
    )COMMENT'科目テーブル';
   
--delete Student Table
DROP TABLE IF EXISTS STUDENT;

--create Student Table
CREATE TABLE STUDENT(
    SID INT NOT NULL COMMENT '学籍番号' AUTO_INCREMENT
    ,SNAME VARCHAR(20) NOT NULL COMMENT '名前'
    ,PASSWORD VARCHAR(50) NOT NULL COMMENT 'パスワード'
    ,GENDER VARCHAR(20) NOT NULL COMMENT '性別'
    ,MID INT NOT NULL COMMENT '専攻'
    ,DPID INT NOT NULL COMMENT '学科'
    ,AUTHORITY INT DEFAULT 0 COMMENT '権利'
    ,PRIMARY KEY(SID)
)COMMENT'学生テーブル';
    
--成績テーブル
DROP TABLE IF EXISTS SCORE;
CREATE TABLE IF NOT EXISTS SCORE(
    SID INTEGER NOT NULL COMMENT'学籍番号'
    ,CID INTEGER NOT NULL COMMENT'科目ID'
    ,MASTER INTEGER DEFAULT 0 NOT NULL COMMENT'修得状況'
    )COMMENT'成績テーブル';
    
--学科テーブル
DROP TABLE IF EXISTS MAJOR;
CREATE TABLE IF NOT EXISTS MAJOR(
    DPID VARCHAR(50) NOT NULL COMMENT'学科ID'
    ,DPNAME VARCHAR(50) NOT NULL COMMENT'学科名'
    ,MID INTEGER NOT NULL COMMENT'専攻ID'
    ,MNAME VARCHAR(50) NOT NULL COMMENT'専攻名'
    ,PRIMARY KEY(MID)
    )COMMENT'専攻テーブル';
    

SELECT SID,sname,PASSWORD FROM STUDENT where sid=2001180178 and password=0708;

--DROP TABLE MANAGER;
--CREATE TABLE MANAGER(
--    MANAGERID INT NOT NULL COMMENT '管理者番号'AUTO_INCREMENT
--   , MANAGERNAME VARCHAR(20) NOT NULL COMMENT '名前'
--    , PASSWORD VARCHAR(20) NOT NULL COMMENT 'パスワード'
--    ,PRIMARY KEY(MANAGERID)
--)COMMENT 'マネージテーブル';

--学生及课程信息查询

SELECT STU.SID, STU.SNAME, C.CID, C.CNAME, S.MASTER FROM STUDENT AS STU JOIN SCORE AS S ON S.SID = STU.SID JOIN COURSE AS C ON S.CID = C.CID;


SELECT * FROM MAJOR M JOIN COURSE C ON M.MID = C.MID;

SELECT STU.SID, STU.SNAME, C.CID, S.MASTER, C.CNAME, C.WEEKDAY, C.CTIME FROM STUDENT AS STU JOIN SCORE AS S ON S.SID = STU.SID JOIN COURSE AS C ON S.CID = C.CID WHERE stu.sID = 2001180178;
select * from student where sid = 2001180178;

SELECT M.DPNAME, M.MID, M.MNAME, C.CID, C.CNAME, C.CTYPE FROM COURSE C JOIN MAJOR M ON C.MID = M.MID;


INSERT INTO COURSE (MID,CID,CNAME,CTYPE) VALUES (1601, 100, '人类行为观察', 1);

SELECT M.DPNAME
,M.MID
,M.MNAME
,C.CID
,C.CNAME
,C.CTYPE
FROM COURSE C JOIN MAJOR M ON C.MID = M.MID WHERE C.CID = 100;
SELECT * FROM STUDENT WHERE SID = 9001;
SELECT * FROM STUDENT WHERE SNAME = 'JACKY';
SELECT STU.SID, STU.SNAME,C.CID, C.CNAME,S.MASTER FROM SCORE S JOIN STUDENT STU ON S.SID = STU.SID JOIN COURSE C ON S.CID = C.CID ;
SELECT STU.SID, STU.SNAME, C.CID, C.CNAME, S.MASTER FROM STUDENT AS STU JOIN SCORE AS S ON S.SID = STU.SID JOIN COURSE AS C ON S.CID = C.CID WHERE S.SID = 2001180178;

SID
